*** Fitting shared propensity score models ***
  |                                                                                                             |   0%Thread 1 returns error: "Insufficient data count for cross validation" when using argument(s): list(cohortMethodDataFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/CmData_l1_t2_c28.zip", createPsArg = list(stopOnError = TRUE, excludeCovariateIds = list(), prior = list(variance = 1, useCrossValidation = TRUE, priorType = "laplace", exclude = 0, neighborhood = NULL, forceIntercept = FALSE, graph = NULL), errorOnHighCorrelation = TRUE, control = list(maxIterations = 1000, autoSearch = TRUE, seed = 1, initialBound = 2, n    gridSteps = 10, threads = 10, startingVariance = 0.01, useKKTSwindle = FALSE, lowerLimit = 0.01, cvRepetitions = 10, noiseLevel = "silent", fold = 10, minCVData = 100, resetCoefficients = FALSE, upperLimit = 20, cvType = "auto", selectorType = "auto", convergenceType = "gradient", tuneSwindle = 10, maxBoundCount = 5, tolerance = 2e-07, algorithm = "ccd"), includeCovariateIds = list(), maxCohortSizeForFitting = 250000), createStudyPopArgs = list(restrictToCommonPeriod = FALSE, removeDuplicateSubjects = "keep all", n    minDaysAtRisk = 1, addExposureDaysToStart = FALSE, riskWindowStart = 1, washoutPeriod = 0, censorAtNewRiskWindow = TRUE, addExposureDaysToEnd = TRUE, priorOutcomeLookback = 30, removeSubjectsWithPriorOutcome = TRUE, riskWindowEnd = 14, firstExposureOnly = FALSE), sharedPsFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/Ps_l1_s1_p1_t2_c28.rds"),TRUE
  |===========================                                                                                  |  25%Thread 2 returns error: "High correlation between covariate(s) and treatment detected. Perhaps you forgot to exclude part of the exposure definition from the covariates?" when using argument(s): list(cohortMethodDataFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/CmData_l1_t137_c143.zip", createPsArg = list(stopOnError = TRUE, excludeCovariateIds = list(), prior = list(variance = 1, useCrossValidation = TRUE, priorType = "laplace", exclude = 0, neighborhood = NULL, forceIntercept = FALSE, graph = NULL), errorOnHighCorrelation = TRUE, control = list(maxIterations = 1000, autoSearch = TRUE, seed = 1, initialBound = 2, n    gridSteps = 10, threads = 10, startingVariance = 0.01, useKKTSwindle = FALSE, lowerLimit = 0.01, cvRepetitions = 10, noiseLevel = "silent", fold = 10, minCVData = 100, resetCoefficients = FALSE, upperLimit = 20, cvType = "auto", selectorType = "auto", convergenceType = "gradient", tuneSwindle = 10, maxBoundCount = 5, tolerance = 2e-07, algorithm = "ccd"), includeCovariateIds = list(), maxCohortSizeForFitting = 250000), createStudyPopArgs = list(restrictToCommonPeriod = FALSE, removeDuplicateSubjects = "keep all", n    minDaysAtRisk = 1, addExposureDaysToStart = FALSE, riskWindowStart = 1, washoutPeriod = 0, censorAtNewRiskWindow = TRUE, addExposureDaysToEnd = TRUE, priorOutcomeLookback = 30, removeSubjectsWithPriorOutcome = TRUE, riskWindowEnd = 14, firstExposureOnly = FALSE), sharedPsFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/Ps_l1_s1_p1_t137_c143.rds"),TRUE
  |======================================================                                                       |  50%Thread 1 returns error: "Insufficient data count for cross validation" when using argument(s): list(cohortMethodDataFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/CmData_l1_t2_c28.zip", createPsArg = list(stopOnError = TRUE, excludeCovariateIds = list(), prior = list(variance = 1, useCrossValidation = TRUE, priorType = "laplace", exclude = 0, neighborhood = NULL, forceIntercept = FALSE, graph = NULL), errorOnHighCorrelation = TRUE, control = list(maxIterations = 1000, autoSearch = TRUE, seed = 1, initialBound = 2, n    gridSteps = 10, threads = 10, startingVariance = 0.01, useKKTSwindle = FALSE, lowerLimit = 0.01, cvRepetitions = 10, noiseLevel = "silent", fold = 10, minCVData = 100, resetCoefficients = FALSE, upperLimit = 20, cvType = "auto", selectorType = "auto", convergenceType = "gradient", tuneSwindle = 10, maxBoundCount = 5, tolerance = 2e-07, algorithm = "ccd"), includeCovariateIds = list(), maxCohortSizeForFitting = 250000), createStudyPopArgs = list(restrictToCommonPeriod = FALSE, removeDuplicateSubjects = "keep all", n    minDaysAtRisk = 1, addExposureDaysToStart = FALSE, riskWindowStart = 1, washoutPeriod = 0, censorAtNewRiskWindow = TRUE, addExposureDaysToEnd = FALSE, priorOutcomeLookback = 30, removeSubjectsWithPriorOutcome = TRUE, riskWindowEnd = 30, firstExposureOnly = FALSE), sharedPsFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/Ps_l1_s2_p1_t2_c28.rds"),TRUE
  |==================================================================================                           |  75%Thread 2 returns error: "High correlation between covariate(s) and treatment detected. Perhaps you forgot to exclude part of the exposure definition from the covariates?" when using argument(s): list(cohortMethodDataFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/CmData_l1_t137_c143.zip", createPsArg = list(stopOnError = TRUE, excludeCovariateIds = list(), prior = list(variance = 1, useCrossValidation = TRUE, priorType = "laplace", exclude = 0, neighborhood = NULL, forceIntercept = FALSE, graph = NULL), errorOnHighCorrelation = TRUE, control = list(maxIterations = 1000, autoSearch = TRUE, seed = 1, initialBound = 2, n    gridSteps = 10, threads = 10, startingVariance = 0.01, useKKTSwindle = FALSE, lowerLimit = 0.01, cvRepetitions = 10, noiseLevel = "silent", fold = 10, minCVData = 100, resetCoefficients = FALSE, upperLimit = 20, cvType = "auto", selectorType = "auto", convergenceType = "gradient", tuneSwindle = 10, maxBoundCount = 5, tolerance = 2e-07, algorithm = "ccd"), includeCovariateIds = list(), maxCohortSizeForFitting = 250000), createStudyPopArgs = list(restrictToCommonPeriod = FALSE, removeDuplicateSubjects = "keep all", n    minDaysAtRisk = 1, addExposureDaysToStart = FALSE, riskWindowStart = 1, washoutPeriod = 0, censorAtNewRiskWindow = TRUE, addExposureDaysToEnd = FALSE, priorOutcomeLookback = 30, removeSubjectsWithPriorOutcome = TRUE, riskWindowEnd = 30, firstExposureOnly = FALSE), sharedPsFile = "/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/results/cmOutput/Ps_l1_s2_p1_t137_c143.rds"),TRUE
  |=============================================================================================================| 100%
Error in ParallelLogger::clusterApply(cluster, modelsToFit, fitSharedPsModel,  : 
  Error(s) when calling function 'fun', see earlier messages for details
In addition: Warning message:
In execute(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema,  :
  fftempdir '/home/idies/workspace/Storage/cli114/persistent/Studies/estimation8.3/Covid19EstimationHydroxychloroquine/FFTemp' not found. Attempting to create folder
Warning: Could not find logger DEFAULT
